-- DROP JOIN LINK TABLES
DROP TABLE IF EXISTS "chat_feed";
DROP TABLE IF EXISTS "chat_article";

-- DROP ENTITY TABLES
DROP TABLE IF EXISTS "articles";
DROP TABLE IF EXISTS "feeds";
DROP TABLE IF EXISTS "chats";