name: goreleaser

# on:
#     release:
#         types: [published]

on:
    push:
        branches:
            - test-deploy

env:
    RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    RAILWAY_SERVICE: Otto

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v4

            # - name: Run GoReleaser
            #   uses: goreleaser/goreleaser-action@v4
            #   with:
            #       distribution: goreleaser
            #       version: latest
            #       args: release --clean
            #       workdir: ./internal
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Use Node 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install Railway
              run: npm i -g @railway/cli

            # - name: Deploy to Railway
            #   uses: Vico1993/railway-deploy@main
            #   with:
            #       service: "Otto"

            - name: Deploy to railway
              run: railway up --service $RAILWAY_SERVICE
