name: Release

on:
    release:
        types: [released]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    RAILWAY_SERVICE: Otto

jobs:
    railway:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Deploy to railway
              uses: bervProject/railway-deploy@0.1.2-beta
              with:
                  service: ${{ env.RAILWAY_SERVICE }}
                  detach: true
