name: Release

on:
    release:
        types: [published]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v4

            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v4
              with:
                  distribution: goreleaser
                  version: latest
                  args: release --clean
                  workdir: ./internal

    railway:
        runs-on: ubuntu-latest
        env:
            RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
            RAILWAY_SERVICE: Otto
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Deploy to railway
              uses: Vico1993/railway-deploy@main
              with:
                  service: ${{ env.RAILWAY_SERVICE }}